language: go
 
go:
    - 1.2

before_script:
    - sudo apt-get update
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    # enable php-fpm
    - sudo cp ~/.phpenv/versions/5.3/etc/php-fpm.conf.default ~/.phpenv/versions/5.3/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/5.3/etc/php.ini
    - ~/.phpenv/versions/5.3/sbin/php-fpm
    # configure apache virtual hosts
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
    - ls -all
    - ls -all ~/.phpenv/versions/
